//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDesc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirSensorsLogs
    {
        public long ident { get; set; }
        public long id { get; set; }
        public decimal temperature { get; set; }
        public decimal humidity { get; set; }
        public System.DateTime date { get; set; }
    }
}
