//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmDesc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mainEntities : DbContext
    {
        public mainEntities()
            : base("name=mainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirSensorsLogs> AirSensorsLogs { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<LandSensorLogs> LandSensorLogs { get; set; }
        public virtual DbSet<Properties> Properties { get; set; }
        public virtual DbSet<AvargeAirLogs> AvargeAirLogs { get; set; }
    }
}
